### ISSUE TITLE
fix python requirements errors 

### ISSUE THREAD

**Issue by awsl-dbq** [snap-stanford/prodigy#1]
Hi ,
 I got some errors 
```
ModuleNotFoundError: No module named 'torch_sparse'
```
It's easy to fix by 
`pip install torch_scatter torch_sparse` 

please add `torch_scatter` and `torch_sparse` to `requirements.txt` for favor

Thanks.

**Comment by q-hwang** [comment]
Thanks for pointing this out and fixed! I thought they should be downloaded with torch_geometric but maybe that has been changed. These two packages sometimes are a bit tricky and need to specify cuda version etc. Here is the reference link in case anyone needs it in the future https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html .
